spring.application.name=NewProject
# setting up the driver url and username is sa which is System Administrator and setting password field as empty
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# giving the path like at which endpoint it is going to hit the database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


#Setting up the Configuration Properties which are required for ques 2

#these properties are defined inside the AppProperties and we are using the prefix defined by @ConfigurationProperties with a prefix so that i can acccess it with the name given
app.name=MyApp
app.version=1.0.5
app.description=Demo Application

# expose all actuator endpoints which is required in Ques4
management.endpoints.web.exposure.include=*

# show full details of health endpoint
management.endpoint.health.show-details=always

#hitting the /actuator endpoint for the health checkups and monitoring
management.endpoints.web.base-path=/actuator

